### ISSUE TITLE
v1.0.1 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#1]
### v1.0.1 Checklist
- [x] Build an update mechanism
- [x] Fix the game scaling selector and power saving modes
- [x] Correct the PSX rumble issue
- [x] Correct PSX and N64 default control issues
- [x] Improve PPSSPP performance
- [x] Distribution Optimizations
- [x] 64bit userland

**Comment by fewtarius** [comment]
Ready to release.
