### ISSUE TITLE
v1.0.3 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#10]
### Necessary to release v1.0.3
- [x] Replace the Anbernic kernel
- [x] ~~Fix the startup console/splash so fbcon works properly~~ (moved to backlog)
- [x] Fix all of the controls issues related to the switch
- [x] Merge Christian's rumble patches for the mgba and flycast cores
- [x] ~~Evaluate adding Flycast/Reicast extreme~~ (moved to backlog)
- [x] Update jslisten to add a global brightness combo 
- [x] Update batocera-es-theme to pull from 351ELEC/themes rather than pastebin so themes can be added/removed simply.
- [x] ~~Evaluate adding PPSSPP libGO2 fork~~ (moved to backlog)
- [x] Explore and resolve issue #4 
- [x] Backend improvements

**Comment by fewtarius** [comment]
Released
