### ISSUE TITLE
v1.0.4 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#27]
- [x] Evaluate correcting the PPSSPP menu size
- [x] Fix delay after sleep before being able to re-enter sleep
- [x] Fix whacky default notification timeout, and move the setting to UI settings where it belongs
- [x] Add notification to break up the blank area between making a menu choice and the choice loading
- [x] Add a simple update script and start scripts for RetroArch 32 & 64bit, and PPSSPP
- [x] ~~Update libpng (and possibly other libraries)~~
- [x] Adjust the brightness hotkeys
- [x] Debug and correct the rumble patch issues
- [x] Apply new default theme
- [x] Set proper aspect ratios
- [x] Complete ports migration
- [x] Add pico-8 to ports
- [x] Disable kmsconsole
- [x] ES System updates .neo, .gbc, wonderswan file types. 
- [x] Beef up the settings menu - add DinguxCommander, and other useful tools

**Comment by fewtarius** [comment]
Ready for RC
