### ISSUE TITLE
v1.0.5 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#31]
- [x] Move themes to a separate submodule or package
- [x] Update hotkeys to the keys requested in the user survey
- [x] Correct issue where deleted configurations are restored on next startup
- [x] Merge external INIs
- [x] Add "safe" overclock keeping within the CPU spec.
- [x] Improve error output logs
- [x] Improve the update script by automatically backing up configurations, and add a script to restore them.
- [x] Remove duplicate port scripts
- [x] Stop building the 32bit media
- [x] Move network settings to the network page (Bluetooth, ssh) and fix them.
- [x] Add functionality to EmulationStation to replace the core overrides in RetroArch

**Comment by fewtarius** [comment]
1.0.5 RC1 has been released.
