### ISSUE TITLE
v1.0.6 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#51]
## Tasks required to be completed before releasing
- [x] Rewrite the emulation start script to be more modular
- [x] Add a battery monitor
- [x] Add online update functionality 
- [x] ~~Switch default game partition to EXFAT (requires a reflash)~~ Reverted due to performance issues.
- [x] Apply RetroArch default hotkeys
- [x] Update Danger Zone to run the backup job and to add a factory reset ~~with no data preservation~~.
- [x] Add dosbox pure
- [x] Fix broken EmulationStation backup
- [x] ~~Evaluate pushing retroarch.cfg to tmpfs on startup~~ (won't do)
- [x] Relocate save and savestate folders to the games volume
- [x] Investigate and correct shaders not binding properly in RetroArch when passed from EmulationStation
- [x] Fix OpenTyrian Port #48 
- [x] Set a default and then remove the weird/confusing ES power settings menu item
- [x] Finish TIC80 integration
- [x] Integrate Pico-8 into systems list
- [x] Move location for DOS, ScummVM, and ResidualVM ES data (gamelist.xml, images, conf files) to the FAT volume

**Comment by fewtarius** [comment]
1.0.6 RC 1 ready to release.
