### ISSUE TITLE
LONG TERM TO-DO

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#6]
- [x] Update the distribution theme
- [x] Set proper aspect ratios for all systems
- [x] Move game configuration to the fat32 partition
- [x] Fix the startup console/splash so fbcon works properly
- [x] Evaluate adding PPSSPP libGO2 fork
- [x] Attempt to correct remaining controls issues
- [x] Swap away from the Anbernic kernel
- [x] ~~Power button press - one second sleep, 3 seconds safe shutdown~~ (won't do)

**Comment by fewtarius** [comment]
Closing, mostly complete or covered in 1.0.6+ lists.
