### ISSUE TITLE
v1.0.7 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#60]
## Required for Release
- [x] Add a community package repository to allow community members to submit packages compiled with buildroot.
- [x] Update EmulationStation
- [x] Fix a bug breaking online updates 
- [x] Fix bezels so they function or remove them from ES. (They do not function properly at the RG351P's native resolution)
- [x] Investigate OpenTyrian loss of controls after wake from sleep. (Issue with the game, nothing we can do)
- [x] If SSH is disabled, do not enable it when enabling WIFI.
- [x] Evaluate and correct DosBox Pure keyboard drift. (Correct in retroarch, set Analog Deadzone to 0.3)
- [x] SNES screen config defaults may not be set right. (could not recreate)
- [x] Update Dreamcast defaults to 640x480. (will not do)
- [x] RPI shaders aren't loading. (Reverted the update as some dependencies were missing)
- [x] Fix OpenBOR scaling (3:2 + RGA then video options to 16:9 in OpenBOR) (temporary)

**Comment by fewtarius** [comment]
1.0.7 RC1 in progress.
