### ISSUE TITLE
v1.0.2 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#7]
### Necessary to release v1.0.2
- [x] Fix 64bit multilib
- [x] Add the missing libretro cores
- [x] Fix RGA scaling
- [x] Fix video playback
- [x] Fix brightness bug
- [x] Fix Drastic downloader

**Comment by fewtarius** [comment]
Released.
