### ISSUE TITLE
v1.0.8 - TRACKER

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#71]
## Required for Release
- [x] Add update channels (Stable, Release Candidate, Nightly)
- [x] Integrate EXFAT 
- [x] Package updates - base OS and emulation (mali-bifrost, retroarch, all cores)
- [x] Add Duke Nukem port
- [x] Drop Half Life port
- [x] Fix Daphne exit control

**Comment by fewtarius** [comment]
Release candidate released.
