### ISSUE TITLE
v1.0.9 - Tracker

### ISSUE THREAD

**Issue by fewtarius** [fewtarius/351ELEC#84]
## Required For Release
- [x] Add multi player support for Diablo and integrate it in EmulationStation
- [x] User interface refinement
- [x] Additional ports - Iortcw, block attack, solarus, uqm (@Cebion)
- [x] Many theme updates (@anthonycaccese and @szalik-rg351)
- [x] Correct WIFI state when loading RetroArch
- [x] Add Amstrad CPC emulator core (crocods)
- [x] Add EasyRPG
- [x] Add uae4arm core
- [x] Update MAME (@claudiojfo)
- [x] Update DosBox Pure to 0.9
- [x] Fix screenshot crash in RetroArch
- [x] Correct additional issues with Mali
- [x] New icons, images, and videos for ports and settings (@szalik-rg351)
- [x] Add 32bit uae4arm (or 64bit if supported)
- [x] Fix Pico-8 arguments issue (@jserodio)
- [x] Add an overclock DTB (optional, manual configuration required)
- [x] Set the brightness to 15 if it's less than 15 on startup
- [x] Correct (hopefully) an issue where the retroarch.cfg becomes a 0 byte file after pressing reset
